### ISSUE TITLE
choose framework Discord.Net or DSharPlus

### ISSUE THREAD

**Issue by AndreyLysenkov** [AndreyLysenkov/psycho-allan#3]
[Discord.Net](https://github.com/RogueException/Discord.Net)
[DSharpPlus](https://github.com/NaamloosDT/DSharpPlus)

**Comment by Huex** [comment]
мех, щас выберешь DSharpPlus, он окажется лучше, и я буду плакать

**Comment by AndreyLysenkov** [comment]
@Huex мех там полный - писосня, практически никем не поддерживаемая, как мне показалось, скорее будет Discord.Net с многопоточностью

**Comment by AndreyLysenkov** [comment]
@Huex https://dsharpplus.emzi0767.com/articles/first_bot.html как тебе (в конце кусочек кода)

**Comment by Huex** [comment]
@AndreyLysenkov в Discord.Net прямо такой же можно написать

**Comment by AndreyLysenkov** [comment]
@Huex ясн 🤔

**Comment by AndreyLysenkov** [comment]
https://github.com/RogueException/Discord.Net
